services:
  mongo:
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - dbdata:/data/db
    networks:
      appNet:
        ipv4_address: 10.0.0.1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: $MONGO_URL
    networks:
      appNet:
        ipv4_address: 10.0.0.2

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_URL: $MONGO_URL
    ports:
      - "80:8080"
    volumes:
      - .:/home/admin/app
      - node_modules:/home/admin/api/app/node_modules
    networks:
      appNet:
        ipv4_address: 10.0.0.3

networks:
  appNet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/28
         gateway: 10.0.0.14

volumes:
  dbdata:
  node_modules: