FROM node:10-alpine

RUN mkdir -p /home/admin/api/app/node_modules && chown -R admin:admin /home/admin/api/app

WORKDIR /home/admin/api/app

COPY package*.json ./

USER node

RUN npm install

COPY --chown=admin . .

EXPOSE 8080

CMD [ "node", "app.js" ]